// JNI prototypes generated by javah
#include "Re.h"

/*
javah -jni Re
c:\"Program Files\Microsoft Visual Studio 12.0\VC\bin\vcvars32"
cl /I"c:\Program Files\java\jdk1.8.0\include" /I"c:\Program Files\java\jdk1.8.0\include\win32" /LD re.cpp /Fere.dll
*/

/*
 * Class:     Re
 * Method:    getCycles
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Re_getCycles
   (JNIEnv *, jclass){
   _asm
   {
      ; Flush the pipeline
      XOR eax, eax
      CPUID
      ; Get RDTSC counter in edx:eax
      RDTSC           ; result in edx:eax
   }
   // return with result in edx:eax
}
