/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re */

#ifndef _Included_Re
#define _Included_Re
#ifdef __cplusplus
extern "C" {
#endif
#undef Re_ALGO_BSP
#define Re_ALGO_BSP 1L
#undef Re_ALGO_BSPP
#define Re_ALGO_BSPP 2L
#undef Re_ALGO_PAT
#define Re_ALGO_PAT 3L
#undef Re_ALGO_EARLEY
#define Re_ALGO_EARLEY 4L
#undef Re_ALGO_JAVA
#define Re_ALGO_JAVA 5L
#undef Re_ALGO_SULZ
#define Re_ALGO_SULZ 6L
#undef Re_ELEKINDSHIFT
#define Re_ELEKINDSHIFT 28L
#undef Re_ELEKIND
#define Re_ELEKIND 268435456L
#undef Re_ELEOPEN
#define Re_ELEOPEN 1L
#undef Re_ELECLOSE
#define Re_ELECLOSE 2L
#undef Re_ELEMASK
#define Re_ELEMASK 268435455L
#undef Re_ELEOPENB
#define Re_ELEOPENB 268435456L
#undef Re_ELECLOSEB
#define Re_ELECLOSEB 536870912L
#undef Re_ELEKMASK
#define Re_ELEKMASK 805306368L
#undef Re_A_LEA
#define Re_A_LEA 0L
#undef Re_A_ALT
#define Re_A_ALT 1L
#undef Re_A_CON
#define Re_A_CON 2L
#undef Re_A_GRO
#define Re_A_GRO 3L
#undef Re_A_EMP
#define Re_A_EMP 4L
#undef Re_A_NUL
#define Re_A_NUL 5L
#undef Re_G_GRO
#define Re_G_GRO 0L
#undef Re_G_OPT
#define Re_G_OPT 1L
#undef Re_G_RE0
#define Re_G_RE0 2L
#undef Re_G_RE1
#define Re_G_RE1 3L
#undef Re_G_BOD
#define Re_G_BOD 4L
#undef Re_G_BOO
#define Re_G_BOO 5L
#undef Re_G_BOR
#define Re_G_BOR 6L
#undef Re_GR_OPEN
#define Re_GR_OPEN 40L
#undef Re_GR_CLOSE
#define Re_GR_CLOSE 41L
#undef Re_EOF
#define Re_EOF 8867L
#undef Re_INT_SHIFTS
#define Re_INT_SHIFTS 5L
#undef Re_INT_MASK
#define Re_INT_MASK 31L
#undef Re_ANYSYMB
#define Re_ANYSYMB 9633L
#undef Re_NSHF
#define Re_NSHF 10L
#undef Re_QUANTUM
#define Re_QUANTUM 1024L
#undef Re_TOKFLAG
#define Re_TOKFLAG -2147483648L
#undef Re_TOKMASK
#define Re_TOKMASK 2147483647L
#undef Re_BTRK_LEA
#define Re_BTRK_LEA 0L
#undef Re_BTRK_ACC
#define Re_BTRK_ACC 1L
#undef Re_BTRK_GOPEN
#define Re_BTRK_GOPEN 2L
#undef Re_BTRK_GCLO
#define Re_BTRK_GCLO 3L
#undef Re_BTRK_AOPEN
#define Re_BTRK_AOPEN 4L
#undef Re_BTRK_ACLO
#define Re_BTRK_ACLO 5L
#undef Re_BTRK_ROPEN
#define Re_BTRK_ROPEN 6L
#undef Re_BTRK_RLOOP
#define Re_BTRK_RLOOP 7L
#undef Re_BTRK_END
#define Re_BTRK_END 8L
#undef Re_ERROR_TIME
#define Re_ERROR_TIME 1L
#undef Re_ERROR_STACK
#define Re_ERROR_STACK 2L
#undef Re_ERROR_MEMORY
#define Re_ERROR_MEMORY 3L
#undef Re_ERROR_NOMATCH
#define Re_ERROR_NOMATCH 4L
#undef Re_NRALGOS
#define Re_NRALGOS 6L
#undef Re_FREQ_NONEST
#define Re_FREQ_NONEST 0L
#undef Re_FREQ_TOTAL
#define Re_FREQ_TOTAL 3L
#undef Re_FREQ_GRNEST
#define Re_FREQ_GRNEST 4L
#undef Re_FREQ_LEV
#define Re_FREQ_LEV 5L
#undef Re_FREQ_NRSONS
#define Re_FREQ_NRSONS 10L
#undef Re_RE_BUCKETS
#define Re_RE_BUCKETS 10L
#undef Re_RE_SAMPLES
#define Re_RE_SAMPLES 100L
#undef Re_TEXT_BUCKETS
#define Re_TEXT_BUCKETS 10L
#undef Re_TEXT_SAMPLES
#define Re_TEXT_SAMPLES 10L
#undef Re_TEXT_SAMPLES_LENGTH
#define Re_TEXT_SAMPLES_LENGTH 100L
/*
 * Class:     Re
 * Method:    getCycles
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Re_getCycles
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
