/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_BSTrans */

#ifndef _Included_Re_BSTrans
#define _Included_Re_BSTrans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
