/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_CombVector */

#ifndef _Included_Re_CombVector
#define _Included_Re_CombVector
#ifdef __cplusplus
extern "C" {
#endif
#undef Re_CombVector_HOLES_ACCESSED
#define Re_CombVector_HOLES_ACCESSED 0L
#undef Re_CombVector_FOLD_ROWS
#define Re_CombVector_FOLD_ROWS 0L
#undef Re_CombVector_PAIRS
#define Re_CombVector_PAIRS 0L
#ifdef __cplusplus
}
#endif
#endif
