/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_TreeNode */

#ifndef _Included_Re_TreeNode
#define _Included_Re_TreeNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
