/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_BSsymbol */

#ifndef _Included_Re_BSsymbol
#define _Included_Re_BSsymbol
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
