/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_BtrkNode */

#ifndef _Included_Re_BtrkNode
#define _Included_Re_BtrkNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
