/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_EarleyTables */

#ifndef _Included_Re_EarleyTables
#define _Included_Re_EarleyTables
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
