/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_IntArray */

#ifndef _Included_Re_IntArray
#define _Included_Re_IntArray
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
