/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_PATrans */

#ifndef _Included_Re_PATrans
#define _Included_Re_PATrans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
