/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_PATStateTable */

#ifndef _Included_Re_PATStateTable
#define _Included_Re_PATStateTable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
