/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Re_Trc */

#ifndef _Included_Re_Trc
#define _Included_Re_Trc
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
